### PR TITLE
Only check every 30 minutes to avoid rate limiting

### PR DESCRIPTION
**Pull request by soerface**

### CODE REVIEW

**Review by malled2002 — APPROVED** [review]

**Comment by dargmuesli** [comment]
Can the branch `update-checker` be removed?

**Comment by soerface** [comment]
Jup. Is there a setting to autoremove branches after merging?

**Comment by dargmuesli** [comment]
Yes, and it's active. The branch for this PR was called `update-checker-sleeptime` and removed successfully, `update-checker` somehow exists as well.

**Pull request merged**
